apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-rbac.yaml
  - 02-config.yaml
  - 03-prometheus.yaml
  - 04-service.yaml
  - 05-node-exporter.yaml
  - 06-kube-state-metrics.yaml
  - 07-alerting-rules.yaml
