apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: livebook
  namespace: livebook
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
      - livebook.segfault.pw
    secretName: livebook-prod-tls
  rules:
  - host: livebook.segfault.pw
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: livebook
            port:
              number: 8080
